version: '3.7'

services:

  # application container
  node:
    container_name: node-backend
    image: nodedocker
    restart: on-failure
    command: "npm run start:pm2-dev"
    build:
        context: ./
        dockerfile: ./docker/Dockerfile
    volumes:
      - ./:/var/www/html/
      - /var/www/html/node_modules
      - ./logs:/var/www/html/logs
    ports:
      - 8000:3000
    depends_on: 
      - postgre
    networks:
      - coffe_network

  postgre:
    image: postgres:latest
    restart: on-failure
    container_name: coffe-database
    environment:
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - "./storage/db-data:/data/db"
    ports:
      - "5432:5432"
    networks:
      - coffe_network
      
#network to hold backend/nginx/postgre
networks:
  coffe_network:
    driver: bridge